### ISSUE TITLE
[HELP] macOS Universal 2 binary

### ISSUE THREAD

**Issue by JayBrown** [ximellon/torrentcheck#1]
Does anyone know how we can build `torrentcheck` on macOS 11 (Big Sur) as a Universal 2 binary with arm64 & x86_64?

It has been removed from Homebrew, so we probably need to do this manually.

```
 ❯ brew info torrentcheck
torrentcheck: stable 1.00 (bottled)
Command-line torrent viewer and hash checker
https://torrentcheck.sourceforge.io/
Disabled because it is not maintained upstream!
```

**Comment by ximellon** [comment]
Sorry. But I'm not a Mac user. I could do it if I get a Mac in the future while it's not gonna happen in the near future.
