### ISSUE TITLE
Minor doc issue; -t flag not implemented

### ISSUE THREAD

**Issue by clach04** [ximellon/torrentcheck#2]
Thanks for making this available!

https://github.com/ximellon/torrentcheck/blob/d322233db8207c6de799aa56b0d8a83fe95960c0/torrentcheck.c#L425

    		printf("Usage: torrentcheck -t torrent-file [-p content-path] [-n] [-h] [-c] [-d]\n");

Based on looking at code and running I *think* `-t` should be removed and readme updated? Looks like torrent filename is positional and required.

**Comment by giovEra** [comment]
This project hosted in [SourceForge] (https://sourceforge.net/projects/torrentcheck/files/torrentcheck-1.00.zip/download) has the _-t_ option implemented and its behavior is the same described in the readme file.

**Comment by ximellon** [comment]
You're right!
